services:
  
  # название сервиса
  postgres:
    # образ
    image: postgres
    # политика перезапуска
    restart: on-failure
    # файл с переменными среды окружения
    env_file:
      - ./db/.env
    # порты
    ports:
      - 5432:5432
    # тома для постоянного хранения данных
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  frontend:
    build: './frontend'
    env_file:
      - ./frontend/.env

  backend:
    build: './backend'
    env_file:
      - ./backend/.env
    volumes:
      - 'static:/usr/src/app/static/'
    

volumes:
  postgres-data:  
  static:


