version: '3.0'

services:
  nest:
    container_name: nest
    build:
      context: ./server
    ports:
      - 3001:3001
      - 3002:3002
      - 9229:9229
      - 3004:5555
    env_file:
      - ./server/.env
    command: ["sh", "run.sh"]
    depends_on:
      - postgres
    restart: always

  react:
    container_name: react
    build:
      context: ./client
    ports:
      - '5173:5173'
    depends_on:
      - nest
    restart: always
  
  postgres:
    # образ
    image: postgres
    # политика перезапуска
    restart: on-failure
    # файл с переменными среды окружения
    env_file:
      - .env
    # порты
    ports:
      - 5432:5432
    # тома для постоянного хранения данных
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


